import path from 'node:path'
import { fileURLToPath } from 'node:url'
import dotenv from 'dotenv'

const contentgenRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
dotenv.config({ path: path.join(contentgenRoot, '.env') })

import { runManifest } from './commands/manifest.js'
import { runGenerateImages } from './commands/generate-images.js'
import { runApply } from './commands/apply.js'
import { runList } from './commands/list.js'

const [command, ...rest] = process.argv.slice(2)

const commands = {
  manifest: runManifest,
  'generate-images': runGenerateImages,
  apply: runApply,
  list: runList,
}

if (!command || command === '--help' || command === '-h') {
  console.log(`
contentgen — landing asset pipeline (project-scoped)

Generates the same asset classes as voidborn:
  domains/     1672×941 png
  cities/      1672×941 png
  cta1/        1376×768 webp
  gamemodel/   1024×1024 webp
  card_types/  640×640 webp

Showcase cards (hero + collection) are generated by cardgen and compiled with FRONTEND_SHOWCASE_ONLY=1.

Project config: projects/{project}/contentgen.json
Prompts source: game/scenes.json, copy/pathways.json, copy/gamemodel.json

Workflow:
  manifest          Build assets/_staging/contentgen/manifest.json
  generate-images   Gemini → staging PNGs
  apply             Resize/encode → projects/{id}/assets/
  list              Status of dest + staging + showcase cards

Examples:
  npm run manifest -- --project=iyashikei
  npm run generate-images -- --project=iyashikei
  npm run generate-images -- --project=iyashikei --kind=domain,city
  npm run generate-images -- --project=iyashikei --id=mori_city_01_moss_shrine --force
  npm run apply -- --project=iyashikei
  npm run list -- --project=iyashikei

Env: contentgen/.env (GEMINI_API_KEY, GEMINI_IMAGE_MODEL, CONTENTGEN_PROJECT)
`)
  process.exit(command ? 0 : 1)
}

const handler = commands[command]
if (!handler) {
  console.error(`Unknown command: ${command}`)
  process.exit(1)
}

handler(rest).catch((err) => {
  console.error(err.message || err)
  process.exit(1)
})
